//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESO
    {
        public Nullable<int> CVE_COMPANIA { get; set; }
        public Nullable<int> CVE_GPO_USUARIO { get; set; }
        public int CVE_TRANSACCION { get; set; }
        public Nullable<int> CVE_PROGRAMA { get; set; }
        public Nullable<int> USAURIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHAHORA_REGISTRO { get; set; }
        public Nullable<int> USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    }
}
