//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACOPIO_MATERIALES
    {
        public ACOPIO_MATERIALES()
        {
            this.ENTREGA_MATERIALES = new HashSet<ENTREGA_MATERIALES>();
            this.SOLICITUD_MATERIALES = new HashSet<SOLICITUD_MATERIALES>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int FOLIO_OT { get; set; }
        public int FOLIO_ACOPIO { get; set; }
        public int NUM_NOMINA_SOLICITA_MATERIALES { get; set; }
        public System.DateTime FECHAHORA_ACOPIO { get; set; }
        public System.DateTime FECHA_ENTREGA_SOLICITADA { get; set; }
        public string ESTATUS_ACOPIO { get; set; }
        public Nullable<System.DateTime> FECHAHORA_ENTREGA { get; set; }
        public Nullable<int> NUM_NOMINA_RECIBE_MATERIALES { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> NUM_NOMINA_AUTORIZA { get; set; }
        public Nullable<System.DateTime> FECHA_AUTORIZA { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual ORDEN_TRABAJO ORDEN_TRABAJO { get; set; }
        public virtual ICollection<ENTREGA_MATERIALES> ENTREGA_MATERIALES { get; set; }
        public virtual ICollection<SOLICITUD_MATERIALES> SOLICITUD_MATERIALES { get; set; }
    }
}
