//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_MANO_OBRA
    {
        public int CVE_COMPANIA { get; set; }
        public int FOLIO_OT { get; set; }
        public int FOLIO_AM { get; set; }
        public int CVE_PUESTO { get; set; }
        public int CVE_UNIDAD_DURACION { get; set; }
        public decimal COSTO_EXTENDIDO { get; set; }
        public decimal VENTA_EXTENDIDO { get; set; }
        public decimal COSTO_UNITARIO { get; set; }
        public decimal POR_MARGEN_GANA { get; set; }
        public decimal PRECIO_VENTA { get; set; }
        public int LP_CVE_MONEDA { get; set; }
        public decimal LP_PRECIO_VENTA { get; set; }
        public Nullable<decimal> LP_COSTO_REAL { get; set; }
        public Nullable<decimal> LP_COSTO_ESTANDAR { get; set; }
        public Nullable<decimal> LP_POR_MARGEN_GANA { get; set; }
        public Nullable<int> LP_CVE_LISTA_PRECIOS { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
        public int NUM_RECURSOS { get; set; }
        public int DURACION { get; set; }
        public int CVE_TIPO_MONEDA { get; set; }
        public decimal PRECIO_VENTA_CAPTURA { get; set; }
    
        public virtual ANALISIS_MARGEN ANALISIS_MARGEN { get; set; }
        public virtual ORDEN_TRABAJO ORDEN_TRABAJO { get; set; }
    }
}
