//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALISIS_MARGEN
    {
        public ANALISIS_MARGEN()
        {
            this.AM_MANO_OBRA = new HashSet<AM_MANO_OBRA>();
            this.AM_MATERIALES = new HashSet<AM_MATERIALES>();
            this.AM_SERVICIOS = new HashSet<AM_SERVICIOS>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int FOLIO_OT { get; set; }
        public int FOLIO_AM { get; set; }
        public decimal TIPO_CAMBIO { get; set; }
        public int CVE_TIPO_MONEDA { get; set; }
        public decimal VENTA_MATERIALES { get; set; }
        public decimal VENTA_MANO_OBRA { get; set; }
        public decimal VENTA_SERVICIOS { get; set; }
        public decimal VENTA_OTROS_GASTOS { get; set; }
        public decimal VENTA_TOTAL { get; set; }
        public decimal COSTO_MATERIALES { get; set; }
        public decimal COSTO_MANO_OBRA { get; set; }
        public decimal COSTO_SERVICIOS { get; set; }
        public decimal COSTO_OTROS_GASTOS { get; set; }
        public decimal COSTO_TOTAL { get; set; }
        public decimal POR_MARGEN_GANANCIA { get; set; }
        public decimal TASA_IVA { get; set; }
        public int USUARIO_ELABORACION { get; set; }
        public System.DateTime FECHAHORA_USUARIO_ELABORACION { get; set; }
        public Nullable<int> USUARIO_GENERA_COTIZA { get; set; }
        public Nullable<System.DateTime> FECHAHORA_GENERA_COTIZA { get; set; }
        public int ESTATUS_COTIZA { get; set; }
        public int AM_CVE_TIPO_CAPTURA { get; set; }
        public int AM_CVE_TIPO_CALCULO { get; set; }
    
        public virtual ICollection<AM_MANO_OBRA> AM_MANO_OBRA { get; set; }
        public virtual ICollection<AM_MATERIALES> AM_MATERIALES { get; set; }
        public virtual ICollection<AM_SERVICIOS> AM_SERVICIOS { get; set; }
        public virtual ORDEN_TRABAJO ORDEN_TRABAJO { get; set; }
        public virtual TIPO_MONEDA TIPO_MONEDA { get; set; }
    }
}
