//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNA_PERSONAL_OT
    {
        public int CVE_COMPANIA { get; set; }
        public int NUM_NOMINA { get; set; }
        public int FOLIO_OT { get; set; }
        public System.DateTime FECHA_ASIGNACION { get; set; }
        public int CVE_PUESTO { get; set; }
        public int RESPONSABLE_EJECUCION { get; set; }
        public decimal SUELDO_DIARIO { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
    }
}
