//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AxesoEntities : DbContext
    {
        public AxesoEntities()
            : base("name=AxesoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACOPIO_MATERIALES> ACOPIO_MATERIALES { get; set; }
        public virtual DbSet<AM_CONDICION_COMERCIAL> AM_CONDICION_COMERCIAL { get; set; }
        public virtual DbSet<AM_MANO_OBRA> AM_MANO_OBRA { get; set; }
        public virtual DbSet<AM_MATERIALES> AM_MATERIALES { get; set; }
        public virtual DbSet<AMBIENTE_TRABAJO> AMBIENTE_TRABAJO { get; set; }
        public virtual DbSet<ANALISIS_MARGEN> ANALISIS_MARGEN { get; set; }
        public virtual DbSet<ASIGNA_PERSONAL_OT> ASIGNA_PERSONAL_OT { get; set; }
        public virtual DbSet<CALENDARIO> CALENDARIO { get; set; }
        public virtual DbSet<CALENDARIO_FESTIVO> CALENDARIO_FESTIVO { get; set; }
        public virtual DbSet<CALENDARIO_LABORAL> CALENDARIO_LABORAL { get; set; }
        public virtual DbSet<CLASIFICACION_SERVICIO> CLASIFICACION_SERVICIO { get; set; }
        public virtual DbSet<CLIENTE_UBICACION> CLIENTE_UBICACION { get; set; }
        public virtual DbSet<CLIENTE_UBICACION_DEPTO> CLIENTE_UBICACION_DEPTO { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<COMPANIA> COMPANIA { get; set; }
        public virtual DbSet<CONCEPTO_FOLIO> CONCEPTO_FOLIO { get; set; }
        public virtual DbSet<CONDICION_COMERCIAL> CONDICION_COMERCIAL { get; set; }
        public virtual DbSet<CONFIGURACION_MO_INDIRECTA> CONFIGURACION_MO_INDIRECTA { get; set; }
        public virtual DbSet<COSTO_MO> COSTO_MO { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DEVOLUCION_MATERIALES> DEVOLUCION_MATERIALES { get; set; }
        public virtual DbSet<DISTRIBUCION_MO> DISTRIBUCION_MO { get; set; }
        public virtual DbSet<DISTRIBUCION_MO_NA> DISTRIBUCION_MO_NA { get; set; }
        public virtual DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ENTREGA_MATERIALES> ENTREGA_MATERIALES { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<ESTATUS_OT> ESTATUS_OT { get; set; }
        public virtual DbSet<ETAPA_OT> ETAPA_OT { get; set; }
        public virtual DbSet<GPO_USUARIO> GPO_USUARIO { get; set; }
        public virtual DbSet<HERRAMIENTAS> HERRAMIENTAS { get; set; }
        public virtual DbSet<INFO_PAIS> INFO_PAIS { get; set; }
        public virtual DbSet<LEVANTAMIENTO_TECNICO> LEVANTAMIENTO_TECNICO { get; set; }
        public virtual DbSet<LINEA_NEGOCIO> LINEA_NEGOCIO { get; set; }
        public virtual DbSet<LISTA_PRECIOS> LISTA_PRECIOS { get; set; }
        public virtual DbSet<LISTA_PRECIOS_MANO_OBRA> LISTA_PRECIOS_MANO_OBRA { get; set; }
        public virtual DbSet<LISTA_PRECIOS_MATERIAL> LISTA_PRECIOS_MATERIAL { get; set; }
        public virtual DbSet<LISTA_PRECIOS_SERVICIO> LISTA_PRECIOS_SERVICIO { get; set; }
        public virtual DbSet<LT_HERRAMIENTAS_OT> LT_HERRAMIENTAS_OT { get; set; }
        public virtual DbSet<LT_MANO_OBRA> LT_MANO_OBRA { get; set; }
        public virtual DbSet<LT_MATERIALES_OT> LT_MATERIALES_OT { get; set; }
        public virtual DbSet<LT_SERVICIOS> LT_SERVICIOS { get; set; }
        public virtual DbSet<MANO_OBRA_PLANEADA> MANO_OBRA_PLANEADA { get; set; }
        public virtual DbSet<MANO_OBRA_REAL> MANO_OBRA_REAL { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<MARCA_SERVICIO> MARCA_SERVICIO { get; set; }
        public virtual DbSet<MATERIALES> MATERIALES { get; set; }
        public virtual DbSet<MUNICIPIO> MUNICIPIO { get; set; }
        public virtual DbSet<ORDEN_TRABAJO> ORDEN_TRABAJO { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PLAN_MAESTRO> PLAN_MAESTRO { get; set; }
        public virtual DbSet<PROGRAMAS_SISTEMA> PROGRAMAS_SISTEMA { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<PUESTOS_RECURSOS> PUESTOS_RECURSOS { get; set; }
        public virtual DbSet<RECHAZO_MOTIVOS> RECHAZO_MOTIVOS { get; set; }
        public virtual DbSet<RECURSOS_OT> RECURSOS_OT { get; set; }
        public virtual DbSet<REGISTRO_ASISTENCIA> REGISTRO_ASISTENCIA { get; set; }
        public virtual DbSet<REGISTRO_CIERRE> REGISTRO_CIERRE { get; set; }
        public virtual DbSet<SERVICIOS> SERVICIOS { get; set; }
        public virtual DbSet<SOLICITUD_MATERIALES> SOLICITUD_MATERIALES { get; set; }
        public virtual DbSet<SUBETAPA_OT> SUBETAPA_OT { get; set; }
        public virtual DbSet<SUCURSAL> SUCURSAL { get; set; }
        public virtual DbSet<TIPO_CANALIZACION> TIPO_CANALIZACION { get; set; }
        public virtual DbSet<TIPO_DISTRIBUCION> TIPO_DISTRIBUCION { get; set; }
        public virtual DbSet<TIPO_MO> TIPO_MO { get; set; }
        public virtual DbSet<TIPO_MONEDA> TIPO_MONEDA { get; set; }
        public virtual DbSet<TIPO_ORDEN> TIPO_ORDEN { get; set; }
        public virtual DbSet<TIPO_PLAFON> TIPO_PLAFON { get; set; }
        public virtual DbSet<TIPO_REGISTRO> TIPO_REGISTRO { get; set; }
        public virtual DbSet<TIPO_SERVICIO> TIPO_SERVICIO { get; set; }
        public virtual DbSet<UNIDAD_DURACION> UNIDAD_DURACION { get; set; }
        public virtual DbSet<UNIDAD_MEDIDA> UNIDAD_MEDIDA { get; set; }
        public virtual DbSet<UNIDAD_SERVICIO> UNIDAD_SERVICIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIO_SUCURSAL> USUARIO_SUCURSAL { get; set; }
        public virtual DbSet<ACCESO> ACCESO { get; set; }
        public virtual DbSet<AM_SERVICIOS> AM_SERVICIOS { get; set; }
        public virtual DbSet<ARCHIVOS_ADJUNTOS> ARCHIVOS_ADJUNTOS { get; set; }
        public virtual DbSet<CONSULTA_PREFERENCIAS> CONSULTA_PREFERENCIAS { get; set; }
        public virtual DbSet<LOCALIDAD> LOCALIDAD { get; set; }
        public virtual DbSet<LoginCorrecto> LoginCorrecto { get; set; }
        public virtual DbSet<PLAN_TRABAJO_OT> PLAN_TRABAJO_OT { get; set; }
        public virtual DbSet<PLAN_TRABAJO_OT_HISTORIAL> PLAN_TRABAJO_OT_HISTORIAL { get; set; }
        public virtual DbSet<TRANSACCION> TRANSACCION { get; set; }
    
        public virtual int sp_UpdatePlanTrabajoOT(Nullable<int> cVE_COMPANIA, Nullable<int> fOLIO_OT, string aCCION, Nullable<int> cVE_ETAPA_OT, Nullable<int> cVE_SUBETAPA_OT, Nullable<int> uSUARIO_RESPONSABLE_SUBETAPA, Nullable<int> pORCENTAJE_AVANCE, Nullable<int> dURACION_ESTIMADA, Nullable<int> cVE_UNIDAD_DURACION, Nullable<System.DateTime> fECHA_INICIO_ESTIMADA, Nullable<System.DateTime> fECHA_FINAL_ESTIMADA, Nullable<int> uSUARIO_ULTIMA_ACTUALIZA, Nullable<System.DateTime> fECHAHORA_ULTIMA_ACTUALIZA, string cOMENTARIOS, string oPERACION)
        {
            var cVE_COMPANIAParameter = cVE_COMPANIA.HasValue ?
                new ObjectParameter("CVE_COMPANIA", cVE_COMPANIA) :
                new ObjectParameter("CVE_COMPANIA", typeof(int));
    
            var fOLIO_OTParameter = fOLIO_OT.HasValue ?
                new ObjectParameter("FOLIO_OT", fOLIO_OT) :
                new ObjectParameter("FOLIO_OT", typeof(int));
    
            var aCCIONParameter = aCCION != null ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(string));
    
            var cVE_ETAPA_OTParameter = cVE_ETAPA_OT.HasValue ?
                new ObjectParameter("CVE_ETAPA_OT", cVE_ETAPA_OT) :
                new ObjectParameter("CVE_ETAPA_OT", typeof(int));
    
            var cVE_SUBETAPA_OTParameter = cVE_SUBETAPA_OT.HasValue ?
                new ObjectParameter("CVE_SUBETAPA_OT", cVE_SUBETAPA_OT) :
                new ObjectParameter("CVE_SUBETAPA_OT", typeof(int));
    
            var uSUARIO_RESPONSABLE_SUBETAPAParameter = uSUARIO_RESPONSABLE_SUBETAPA.HasValue ?
                new ObjectParameter("USUARIO_RESPONSABLE_SUBETAPA", uSUARIO_RESPONSABLE_SUBETAPA) :
                new ObjectParameter("USUARIO_RESPONSABLE_SUBETAPA", typeof(int));
    
            var pORCENTAJE_AVANCEParameter = pORCENTAJE_AVANCE.HasValue ?
                new ObjectParameter("PORCENTAJE_AVANCE", pORCENTAJE_AVANCE) :
                new ObjectParameter("PORCENTAJE_AVANCE", typeof(int));
    
            var dURACION_ESTIMADAParameter = dURACION_ESTIMADA.HasValue ?
                new ObjectParameter("DURACION_ESTIMADA", dURACION_ESTIMADA) :
                new ObjectParameter("DURACION_ESTIMADA", typeof(int));
    
            var cVE_UNIDAD_DURACIONParameter = cVE_UNIDAD_DURACION.HasValue ?
                new ObjectParameter("CVE_UNIDAD_DURACION", cVE_UNIDAD_DURACION) :
                new ObjectParameter("CVE_UNIDAD_DURACION", typeof(int));
    
            var fECHA_INICIO_ESTIMADAParameter = fECHA_INICIO_ESTIMADA.HasValue ?
                new ObjectParameter("FECHA_INICIO_ESTIMADA", fECHA_INICIO_ESTIMADA) :
                new ObjectParameter("FECHA_INICIO_ESTIMADA", typeof(System.DateTime));
    
            var fECHA_FINAL_ESTIMADAParameter = fECHA_FINAL_ESTIMADA.HasValue ?
                new ObjectParameter("FECHA_FINAL_ESTIMADA", fECHA_FINAL_ESTIMADA) :
                new ObjectParameter("FECHA_FINAL_ESTIMADA", typeof(System.DateTime));
    
            var uSUARIO_ULTIMA_ACTUALIZAParameter = uSUARIO_ULTIMA_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ULTIMA_ACTUALIZA", uSUARIO_ULTIMA_ACTUALIZA) :
                new ObjectParameter("USUARIO_ULTIMA_ACTUALIZA", typeof(int));
    
            var fECHAHORA_ULTIMA_ACTUALIZAParameter = fECHAHORA_ULTIMA_ACTUALIZA.HasValue ?
                new ObjectParameter("FECHAHORA_ULTIMA_ACTUALIZA", fECHAHORA_ULTIMA_ACTUALIZA) :
                new ObjectParameter("FECHAHORA_ULTIMA_ACTUALIZA", typeof(System.DateTime));
    
            var cOMENTARIOSParameter = cOMENTARIOS != null ?
                new ObjectParameter("COMENTARIOS", cOMENTARIOS) :
                new ObjectParameter("COMENTARIOS", typeof(string));
    
            var oPERACIONParameter = oPERACION != null ?
                new ObjectParameter("OPERACION", oPERACION) :
                new ObjectParameter("OPERACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdatePlanTrabajoOT", cVE_COMPANIAParameter, fOLIO_OTParameter, aCCIONParameter, cVE_ETAPA_OTParameter, cVE_SUBETAPA_OTParameter, uSUARIO_RESPONSABLE_SUBETAPAParameter, pORCENTAJE_AVANCEParameter, dURACION_ESTIMADAParameter, cVE_UNIDAD_DURACIONParameter, fECHA_INICIO_ESTIMADAParameter, fECHA_FINAL_ESTIMADAParameter, uSUARIO_ULTIMA_ACTUALIZAParameter, fECHAHORA_ULTIMA_ACTUALIZAParameter, cOMENTARIOSParameter, oPERACIONParameter);
        }
    }
}
