//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_UBICACION
    {
        public CLIENTE_UBICACION()
        {
            this.CLIENTE_UBICACION_DEPTO = new HashSet<CLIENTE_UBICACION_DEPTO>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int CVE_CLIENTE { get; set; }
        public int CVE_UBICACION { get; set; }
        public string DESC_UBICACION { get; set; }
        public string CALLE_CLIENTE_UBICACION { get; set; }
        public string NUM_EXTERIOR_UBICACION { get; set; }
        public string INTERIOR_UBICACION { get; set; }
        public string COLONIA_CLIENTE_UBICACION { get; set; }
        public int CP_CLIENTE_UBICACION { get; set; }
        public int CVE_PAIS { get; set; }
        public int CVE_ESTADO { get; set; }
        public int CVE_MUNICIPIO { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual ICollection<CLIENTE_UBICACION_DEPTO> CLIENTE_UBICACION_DEPTO { get; set; }
    }
}
