//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_UBICACION_DEPTO
    {
        public CLIENTE_UBICACION_DEPTO()
        {
            this.ORDEN_TRABAJO = new HashSet<ORDEN_TRABAJO>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int CVE_CLIENTE { get; set; }
        public int CVE_UBICACION { get; set; }
        public int CVE_DEPTO { get; set; }
        public string NOM_CONTACTO { get; set; }
        public string TEL1_CONTACTO { get; set; }
        public string EXT1_CONTACTO { get; set; }
        public string TEL2_CONTACTO { get; set; }
        public string EXT2_CONTACTO { get; set; }
        public string CEL_CONTACTO { get; set; }
        public string EMAIL_CONTACTO { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual CLIENTE_UBICACION CLIENTE_UBICACION { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual ICollection<ORDEN_TRABAJO> ORDEN_TRABAJO { get; set; }
    }
}
