//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANIA
    {
        public COMPANIA()
        {
            this.CALENDARIO = new HashSet<CALENDARIO>();
            this.CALENDARIO_FESTIVO = new HashSet<CALENDARIO_FESTIVO>();
            this.CALENDARIO_LABORAL = new HashSet<CALENDARIO_LABORAL>();
            this.CLIENTES = new HashSet<CLIENTES>();
            this.EMPRESA = new HashSet<EMPRESA>();
            this.LISTA_PRECIOS = new HashSet<LISTA_PRECIOS>();
            this.ORDEN_TRABAJO = new HashSet<ORDEN_TRABAJO>();
            this.SUCURSAL = new HashSet<SUCURSAL>();
            this.USUARIO = new HashSet<USUARIO>();
            this.USUARIO_SUCURSAL = new HashSet<USUARIO_SUCURSAL>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public string RFC_COMPANIA { get; set; }
        public string NOMBRE_COMPANIA { get; set; }
        public string CALLE_COMPANIA { get; set; }
        public string NUM_EXTERIOR_COMPANIA { get; set; }
        public string INTERIOR_COMPANIA { get; set; }
        public string COLONIA_COMPANIA { get; set; }
        public Nullable<int> CP_COMPANIA { get; set; }
        public Nullable<int> CVE_PAIS { get; set; }
        public Nullable<int> CVE_ESTADO { get; set; }
        public Nullable<int> CVE_MUNICIPIO { get; set; }
        public string CONTACTO_COMPANIA { get; set; }
        public string TELEFONO1_COMPANIA { get; set; }
        public string EXTENSION1_COMPANIA { get; set; }
        public string TELEFONO2_COMPANIA { get; set; }
        public string EXTENSION2_COMPANIA { get; set; }
        public string CELULAR_CONTACTO { get; set; }
        public string EMAIL_COMPANIA { get; set; }
        public Nullable<int> AM_CVE_TIPO_CAPTURA { get; set; }
        public Nullable<int> AM_CVE_TIPO_CALCULO { get; set; }
        public Nullable<decimal> TASA_IVA { get; set; }
        public string LOGO_NOMBRE_ARCHIVO { get; set; }
        public Nullable<int> USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHAHORA_REGISTRO { get; set; }
        public Nullable<int> USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
        public string FONDO_NOMBRE_ARCHIVO { get; set; }
        public int NIVEL1_ETAPA { get; set; }
        public int NIVEL1_SUBETAPA { get; set; }
        public int NIVEL1_ESTATUS { get; set; }
        public int NIVEL2_ETAPA { get; set; }
        public int NIVEL2_SUBETAPA { get; set; }
        public int NIVEL2_ESTATUS { get; set; }
        public int NIVEL3_ETAPA { get; set; }
        public int NIVEL3_SUBETAPA { get; set; }
        public int NIVEL3_ESTATUS { get; set; }
        public int NIVEL4_ETAPA { get; set; }
        public int NIVEL4_SUBETAPA { get; set; }
        public int NIVEL4_ESTATUS { get; set; }
        public int NIVEL5_ETAPA { get; set; }
        public int NIVEL5_SUBETAPA { get; set; }
        public int NIVEL5_ESTATUS { get; set; }
        public int ESTATUS_PERDIDA { get; set; }
        public int ESTATUS_RECHAZADA { get; set; }
        public int ESTATUS_APROBADA { get; set; }
        public int ESTATUS_CERRADA { get; set; }
        public string REPORTE_LOGO1 { get; set; }
    
        public virtual ICollection<CALENDARIO> CALENDARIO { get; set; }
        public virtual ICollection<CALENDARIO_FESTIVO> CALENDARIO_FESTIVO { get; set; }
        public virtual ICollection<CALENDARIO_LABORAL> CALENDARIO_LABORAL { get; set; }
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
        public virtual PAIS PAIS { get; set; }
        public virtual ICollection<EMPRESA> EMPRESA { get; set; }
        public virtual ICollection<LISTA_PRECIOS> LISTA_PRECIOS { get; set; }
        public virtual ICollection<ORDEN_TRABAJO> ORDEN_TRABAJO { get; set; }
        public virtual ICollection<SUCURSAL> SUCURSAL { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        public virtual ICollection<USUARIO_SUCURSAL> USUARIO_SUCURSAL { get; set; }
    }
}
