//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA_PREFERENCIAS
    {
        public int CVE_COMPANIA { get; set; }
        public int ID_USUARIO { get; set; }
        public int PREFERENCIA { get; set; }
        public string DES_PREFERENCIA { get; set; }
        public bool SUCURSAL { get; set; }
        public bool FOLIO_OT { get; set; }
        public bool AVANCE { get; set; }
        public bool ESTATUS { get; set; }
        public bool TIPO_OT { get; set; }
        public bool NOMBRE_SERVICIO { get; set; }
        public bool TIPO_SERVICIO { get; set; }
        public bool LINEA_NEGOCIO { get; set; }
        public bool RESPONSABLE { get; set; }
        public bool EMPRESA { get; set; }
        public bool CLIENTE { get; set; }
        public bool UBICACION { get; set; }
        public bool DEPARTAMENTO { get; set; }
        public bool ANIO { get; set; }
        public bool MES { get; set; }
        public bool FECHA_INICIAL { get; set; }
        public bool FECHA_FINAL { get; set; }
        public bool FECHA_AUTORIZACION { get; set; }
        public bool PAIS { get; set; }
        public bool ESTADO { get; set; }
        public bool MUNICIPIO { get; set; }
        public bool VENTA_OT { get; set; }
        public bool VENTA_MO { get; set; }
        public bool VENTA_MATERIALES { get; set; }
        public bool VENTA_SERVICIOS { get; set; }
        public bool COSTO_OT { get; set; }
        public bool COSTO_MO { get; set; }
        public bool COSTO_MATERIALES { get; set; }
        public bool COSTO_SERVICIOS { get; set; }
        public bool UTILIDAD_MONEDA { get; set; }
        public bool UTILIDAD_PORCENTAJE { get; set; }
        public bool UTILIDAD_MO { get; set; }
        public bool UTILIDAD_MATERIALES { get; set; }
        public bool UTILIDAD_SERVICIOS { get; set; }
        public bool COSTO_OT_REAL { get; set; }
        public bool COSTO_MO_REAL { get; set; }
        public bool COSTO_MATERIALES_REAL { get; set; }
        public bool COSTO_SERVICIOS_REAL { get; set; }
        public bool UTILIDAD_MONEDA_REAL { get; set; }
        public bool UTILIDAD_PORCENTAJE_REAL { get; set; }
        public bool UTILIDAD_MO_REAL { get; set; }
        public bool UTILIDAD_MATERIALES_REAL { get; set; }
        public bool UTILIDAD_SERVICIOS_REAL { get; set; }
    }
}
