//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVOLUCION_MATERIALES
    {
        public int CVE_COMPANIA { get; set; }
        public int FOLIO_OT { get; set; }
        public int FOLIO_MATERIAL_DEVUELTO { get; set; }
        public int FOLIO_AREA_TRABAJO { get; set; }
        public string NUM_PARTE_MATERIAL { get; set; }
        public int NUM_NOMINA_DEVUELVE_MATERIALES { get; set; }
        public System.DateTime FECHA_DEVOLUCION { get; set; }
        public decimal CANTIDAD_DEVUELTA { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual LEVANTAMIENTO_TECNICO LEVANTAMIENTO_TECNICO { get; set; }
        public virtual MATERIALES MATERIALES { get; set; }
    }
}
