//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUCION_MO
    {
        public int CVE_COMPANIA { get; set; }
        public int TIPO_MO { get; set; }
        public System.DateTime FECHA { get; set; }
        public int NUM_NOMINA { get; set; }
        public decimal SUELDO_DIARIO { get; set; }
    }
}
