//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        public EMPLEADOS()
        {
            this.MANO_OBRA_PLANEADA = new HashSet<MANO_OBRA_PLANEADA>();
            this.MANO_OBRA_REAL = new HashSet<MANO_OBRA_REAL>();
            this.REGISTRO_ASISTENCIA = new HashSet<REGISTRO_ASISTENCIA>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int NUM_NOMINA { get; set; }
        public bool EMPLEADO_ACTIVO { get; set; }
        public string NOMBRE { get; set; }
        public string AP_PATERNO { get; set; }
        public string AP_MATERNO { get; set; }
        public decimal SUELDO_DIARIO { get; set; }
        public int CVE_TIPO_MONEDA { get; set; }
        public int CVE_PUESTO { get; set; }
        public string RFC_EMPLEADO { get; set; }
        public string NSS_EMPLEADO { get; set; }
        public string CALLE_EMPLEADO { get; set; }
        public string NUM_EXTERIOR_EMPLEADO { get; set; }
        public string NUM_INTERIOR_EMPLEADO { get; set; }
        public string COLONIA_EMPLEADO { get; set; }
        public Nullable<int> CP_EMPLEADO { get; set; }
        public Nullable<int> CVE_PAIS { get; set; }
        public Nullable<int> CVE_ESTADO { get; set; }
        public Nullable<int> CVE_MUNICIPIO { get; set; }
        public string TEL_EMPLEADO { get; set; }
        public string CEL_EMPLEADO { get; set; }
        public string EMAIL_EMPLEADO { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual TIPO_MONEDA TIPO_MONEDA { get; set; }
        public virtual ICollection<MANO_OBRA_PLANEADA> MANO_OBRA_PLANEADA { get; set; }
        public virtual ICollection<MANO_OBRA_REAL> MANO_OBRA_REAL { get; set; }
        public virtual ICollection<REGISTRO_ASISTENCIA> REGISTRO_ASISTENCIA { get; set; }
    }
}
