//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public EMPRESA()
        {
            this.CLIENTES = new HashSet<CLIENTES>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int CVE_EMPRESA { get; set; }
        public string DES_EMPRESA { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
        public virtual COMPANIA COMPANIA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
