//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETAPA_OT
    {
        public ETAPA_OT()
        {
            this.ORDEN_TRABAJO = new HashSet<ORDEN_TRABAJO>();
            this.PLAN_MAESTRO = new HashSet<PLAN_MAESTRO>();
            this.PLAN_TRABAJO_OT = new HashSet<PLAN_TRABAJO_OT>();
            this.PLAN_TRABAJO_OT_HISTORIAL = new HashSet<PLAN_TRABAJO_OT_HISTORIAL>();
            this.SUBETAPA_OT = new HashSet<SUBETAPA_OT>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int CVE_ETAPA_OT { get; set; }
        public string DES_ETAPA_OT { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual ICollection<ORDEN_TRABAJO> ORDEN_TRABAJO { get; set; }
        public virtual ICollection<PLAN_MAESTRO> PLAN_MAESTRO { get; set; }
        public virtual ICollection<PLAN_TRABAJO_OT> PLAN_TRABAJO_OT { get; set; }
        public virtual ICollection<PLAN_TRABAJO_OT_HISTORIAL> PLAN_TRABAJO_OT_HISTORIAL { get; set; }
        public virtual ICollection<SUBETAPA_OT> SUBETAPA_OT { get; set; }
    }
}
