//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPO_USUARIO
    {
        public GPO_USUARIO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int CVE_GPO_USUARIO { get; set; }
        public string DES_GPO_USUARIO { get; set; }
        public Nullable<int> USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHAHORA_REGISTRO { get; set; }
        public Nullable<int> USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
        public Nullable<bool> SW_ADMINISTRADOR { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
