//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_PRECIOS_MANO_OBRA
    {
        public int CVE_COMPANIA { get; set; }
        public int CVE_LISTA_PRECIOS { get; set; }
        public int CVE_PUESTO { get; set; }
        public int CVE_UNIDAD_DURACION { get; set; }
        public Nullable<decimal> COSTO_REAL { get; set; }
        public Nullable<decimal> COSTO_ESTANDAR { get; set; }
        public decimal PRECIO_VENTA { get; set; }
        public int CVE_TIPO_MONEDA { get; set; }
        public decimal POR_MARGEN_GANA { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_USUARIO_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual TIPO_MONEDA TIPO_MONEDA { get; set; }
        public virtual UNIDAD_DURACION UNIDAD_DURACION { get; set; }
    }
}
