//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANO_OBRA_REAL
    {
        public int CVE_COMPANIA { get; set; }
        public int FOLIO_OT { get; set; }
        public int NUM_NOMINA { get; set; }
        public int DURACION { get; set; }
        public int CVE_UNIDAD_DURACION { get; set; }
        public System.DateTime FECHA_INICIAL_ASIGNACION { get; set; }
        public System.DateTime FECHA_FINAL_ASIGNACION { get; set; }
        public decimal SUELDO_DIARIO { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual ORDEN_TRABAJO ORDEN_TRABAJO { get; set; }
        public virtual UNIDAD_DURACION UNIDAD_DURACION { get; set; }
    }
}
