//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_TRABAJO
    {
        public ORDEN_TRABAJO()
        {
            this.ACOPIO_MATERIALES = new HashSet<ACOPIO_MATERIALES>();
            this.AM_MANO_OBRA = new HashSet<AM_MANO_OBRA>();
            this.AM_MATERIALES = new HashSet<AM_MATERIALES>();
            this.ANALISIS_MARGEN = new HashSet<ANALISIS_MARGEN>();
            this.LEVANTAMIENTO_TECNICO = new HashSet<LEVANTAMIENTO_TECNICO>();
            this.LT_HERRAMIENTAS_OT = new HashSet<LT_HERRAMIENTAS_OT>();
            this.LT_MANO_OBRA = new HashSet<LT_MANO_OBRA>();
            this.LT_MATERIALES_OT = new HashSet<LT_MATERIALES_OT>();
            this.LT_SERVICIOS = new HashSet<LT_SERVICIOS>();
            this.MANO_OBRA_PLANEADA = new HashSet<MANO_OBRA_PLANEADA>();
            this.MANO_OBRA_REAL = new HashSet<MANO_OBRA_REAL>();
            this.ARCHIVOS_ADJUNTOS = new HashSet<ARCHIVOS_ADJUNTOS>();
            this.PLAN_TRABAJO_OT_HISTORIAL = new HashSet<PLAN_TRABAJO_OT_HISTORIAL>();
            this.PLAN_TRABAJO_OT = new HashSet<PLAN_TRABAJO_OT>();
            this.RECURSOS_OT = new HashSet<RECURSOS_OT>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int FOLIO_OT { get; set; }
        public Nullable<int> CVE_SUCURSAL_COMPANIA { get; set; }
        public Nullable<int> CVE_TIPO_OT { get; set; }
        public Nullable<int> CVE_ETAPA_OT { get; set; }
        public Nullable<int> CVE_SUBETAPA_OT { get; set; }
        public Nullable<int> CVE_ESTATUS_OT { get; set; }
        public Nullable<int> CVE_CLIENTE { get; set; }
        public Nullable<int> CVE_UBICACION { get; set; }
        public Nullable<int> CVE_DEPTO { get; set; }
        public string NOM_SOLICITANTE { get; set; }
        public string NOMBRE_SERVICIO { get; set; }
        public string DES_GRAL_SERVICIO { get; set; }
        public Nullable<int> CVE_AMBIENTE_TRABAJO { get; set; }
        public Nullable<int> CVE_TIPO_SERVICIO { get; set; }
        public Nullable<int> CVE_LINEA_NEGOCIO { get; set; }
        public Nullable<System.DateTime> FECHA_REQUERIDA { get; set; }
        public Nullable<int> REQUIERE_LEVANTAMIENTO { get; set; }
        public Nullable<int> USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHAHORA_REGISTRO { get; set; }
        public Nullable<int> USUARIO_ULTIMA_ACTUALIZA { get; set; }
        public Nullable<System.DateTime> FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
        public Nullable<int> USUARIO_RESPONSABLE_OT { get; set; }
        public Nullable<System.DateTime> FECHAHORA_RESPONSABLE_OT { get; set; }
        public Nullable<int> USUARIO_RESPONSABLE_EJECUTA { get; set; }
        public Nullable<System.DateTime> FECHAHORA_RESPONSABLE_EJECUTA { get; set; }
        public Nullable<int> USUARIO_RECHAZO { get; set; }
        public Nullable<System.DateTime> FECHAHORA_RECHAZO { get; set; }
        public Nullable<int> USUARIO_AUTORIZACION { get; set; }
        public Nullable<System.DateTime> FECHAHORA_AUTORIZACION { get; set; }
        public Nullable<int> CVE_RECHAZO { get; set; }
        public int PESTANA_NIVEL { get; set; }
        public int NUM_COTIZACION_APROBADA { get; set; }
    
        public virtual ICollection<ACOPIO_MATERIALES> ACOPIO_MATERIALES { get; set; }
        public virtual ICollection<AM_MANO_OBRA> AM_MANO_OBRA { get; set; }
        public virtual ICollection<AM_MATERIALES> AM_MATERIALES { get; set; }
        public virtual AMBIENTE_TRABAJO AMBIENTE_TRABAJO { get; set; }
        public virtual ICollection<ANALISIS_MARGEN> ANALISIS_MARGEN { get; set; }
        public virtual CLIENTE_UBICACION_DEPTO CLIENTE_UBICACION_DEPTO { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual COMPANIA COMPANIA { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual ESTATUS_OT ESTATUS_OT { get; set; }
        public virtual ETAPA_OT ETAPA_OT { get; set; }
        public virtual ICollection<LEVANTAMIENTO_TECNICO> LEVANTAMIENTO_TECNICO { get; set; }
        public virtual LINEA_NEGOCIO LINEA_NEGOCIO { get; set; }
        public virtual ICollection<LT_HERRAMIENTAS_OT> LT_HERRAMIENTAS_OT { get; set; }
        public virtual ICollection<LT_MANO_OBRA> LT_MANO_OBRA { get; set; }
        public virtual ICollection<LT_MATERIALES_OT> LT_MATERIALES_OT { get; set; }
        public virtual ICollection<LT_SERVICIOS> LT_SERVICIOS { get; set; }
        public virtual ICollection<MANO_OBRA_PLANEADA> MANO_OBRA_PLANEADA { get; set; }
        public virtual ICollection<MANO_OBRA_REAL> MANO_OBRA_REAL { get; set; }
        public virtual ICollection<ARCHIVOS_ADJUNTOS> ARCHIVOS_ADJUNTOS { get; set; }
        public virtual RECHAZO_MOTIVOS RECHAZO_MOTIVOS { get; set; }
        public virtual TIPO_ORDEN TIPO_ORDEN { get; set; }
        public virtual TIPO_SERVICIO TIPO_SERVICIO { get; set; }
        public virtual ICollection<PLAN_TRABAJO_OT_HISTORIAL> PLAN_TRABAJO_OT_HISTORIAL { get; set; }
        public virtual ICollection<PLAN_TRABAJO_OT> PLAN_TRABAJO_OT { get; set; }
        public virtual ICollection<RECURSOS_OT> RECURSOS_OT { get; set; }
    }
}
