//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_TRABAJO_OT_HISTORIAL
    {
        public int CVE_COMPANIA { get; set; }
        public int FOLIO_OT { get; set; }
        public string ACCION { get; set; }
        public int CVE_ETAPA_OT { get; set; }
        public int CVE_SUBETAPA_OT { get; set; }
        public decimal DURACION_ESTIMADA { get; set; }
        public int CVE_UNIDAD_DURACION { get; set; }
        public Nullable<int> PORCENTAJE_AVANCE { get; set; }
        public Nullable<int> USUARIO_RESPONSABLE_SUBETAPA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_ESTIMADA { get; set; }
        public Nullable<System.DateTime> FECHA_FINAL_ESTIMADA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_REAL { get; set; }
        public Nullable<System.DateTime> FECHA_FINAL_REAL { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_USUARIO_REGISTRO { get; set; }
        public int USUARIO_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ACTUALIZACION { get; set; }
        public int PORCENTAJE_AVANCE_ETAPA { get; set; }
        public string COMENTARIOS { get; set; }
        public int ID { get; set; }
    
        public virtual ETAPA_OT ETAPA_OT { get; set; }
        public virtual ORDEN_TRABAJO ORDEN_TRABAJO { get; set; }
        public virtual SUBETAPA_OT SUBETAPA_OT { get; set; }
        public virtual UNIDAD_DURACION UNIDAD_DURACION { get; set; }
    }
}
