//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_CIERRE
    {
        public int CVE_COMPANIA { get; set; }
        public int FOLIO { get; set; }
        public System.DateTime FECHA_ULTIMO_CIERRE { get; set; }
        public int USUARIO_REGISTRO { get; set; }
    }
}
