//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_MATERIALES
    {
        public int CVE_COMPANIA { get; set; }
        public int FOLIO_OT { get; set; }
        public int FOLIO_ACOPIO { get; set; }
        public int FOLIO_MATERIAL_SOLICITADO { get; set; }
        public int FOLIO_AREA_TRABAJO { get; set; }
        public string NUM_PARTE_MATERIAL { get; set; }
        public decimal CANTIDAD_REQUERIDA_LT { get; set; }
        public decimal CANTIDAD_ENTREGADA { get; set; }
        public decimal CANTIDAD_PENDIENTE_ENTREGAR { get; set; }
        public decimal CANTIDAD_SOLICITADA_ACOPIO { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual ACOPIO_MATERIALES ACOPIO_MATERIALES { get; set; }
        public virtual LEVANTAMIENTO_TECNICO LEVANTAMIENTO_TECNICO { get; set; }
        public virtual MATERIALES MATERIALES { get; set; }
    }
}
