//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBETAPA_OT
    {
        public SUBETAPA_OT()
        {
            this.PLAN_TRABAJO_OT_HISTORIAL = new HashSet<PLAN_TRABAJO_OT_HISTORIAL>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int CVE_ETAPA_OT { get; set; }
        public int CVE_SUBETAPA_OT { get; set; }
        public string DES_SUBETAPA_OT { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual ETAPA_OT ETAPA_OT { get; set; }
        public virtual PLAN_MAESTRO PLAN_MAESTRO { get; set; }
        public virtual ICollection<PLAN_TRABAJO_OT_HISTORIAL> PLAN_TRABAJO_OT_HISTORIAL { get; set; }
    }
}
