//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        public SUCURSAL()
        {
            this.CALENDARIO = new HashSet<CALENDARIO>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int CVE_SUCURSAL_COMPANIA { get; set; }
        public string NOMBRE_SUCURSAL_COMPANIA { get; set; }
        public string CALLE_SUCURSAL_COMPANIA { get; set; }
        public string NUM_EXTERIOR_SUCURSAL_COMPANIA { get; set; }
        public string NUM_INTERIOR_SUCURSAL_COMPANIA { get; set; }
        public string COLONIA_SUCURSAL_COMPANIA { get; set; }
        public Nullable<int> CP_SUCURSAL_COMPANIA { get; set; }
        public Nullable<int> CVE_PAIS { get; set; }
        public Nullable<int> CVE_ESTADO { get; set; }
        public Nullable<int> CVE_MUNICIPIO { get; set; }
        public Nullable<int> CVE_CONTACTO_SUCURSAL { get; set; }
        public string CONTACTO_SUCURSAL_TELEFONO1 { get; set; }
        public string CONTACTO_SUCURSAL_TELEFONO2 { get; set; }
        public string CONTACTO_SUCURSAL_EXT1 { get; set; }
        public string CONTACTO_SUCURSAL_EXT2 { get; set; }
        public string CONTACTO_SUCURSAL_EMAIL { get; set; }
        public string CONTACTO_SUCURSAL_CELULAR { get; set; }
        public Nullable<int> USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHAHORA_USUARIO_REGISTRO { get; set; }
        public Nullable<int> USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual ICollection<CALENDARIO> CALENDARIO { get; set; }
        public virtual COMPANIA COMPANIA { get; set; }
        public virtual PAIS PAIS { get; set; }
    }
}
