//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DISTRIBUCION
    {
        public int CVE_COMPANIA { get; set; }
        public int TIPO_DISTRIBUCION1 { get; set; }
        public string DES_TIPO_DISTRIBUCION { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHA_ULTIMA_ACTUALIZACION { get; set; }
    }
}
