//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION
    {
        public Nullable<int> CVE_TRANSACCION { get; set; }
        public string DESCRIPCION_TRANSACCION { get; set; }
        public int CVE_PROGRAMA { get; set; }
    }
}
