//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxesoMovil
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDAD_SERVICIO
    {
        public UNIDAD_SERVICIO()
        {
            this.LISTA_PRECIOS_SERVICIO = new HashSet<LISTA_PRECIOS_SERVICIO>();
            this.SERVICIOS = new HashSet<SERVICIOS>();
            this.AM_SERVICIOS = new HashSet<AM_SERVICIOS>();
            this.LT_SERVICIOS = new HashSet<LT_SERVICIOS>();
        }
    
        public int CVE_COMPANIA { get; set; }
        public int CVE_UNIDAD_SERVICIO { get; set; }
        public string DES_UNIDAD_SERVICIO { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public System.DateTime FECHAHORA_REGISTRO { get; set; }
        public int USUARIO_ULTIMA_ACTUALIZACION { get; set; }
        public System.DateTime FECHAHORA_ULTIMA_ACTUALIZACION { get; set; }
    
        public virtual ICollection<LISTA_PRECIOS_SERVICIO> LISTA_PRECIOS_SERVICIO { get; set; }
        public virtual ICollection<SERVICIOS> SERVICIOS { get; set; }
        public virtual ICollection<AM_SERVICIOS> AM_SERVICIOS { get; set; }
        public virtual ICollection<LT_SERVICIOS> LT_SERVICIOS { get; set; }
    }
}
